/* Cosmic Atlas — celestial bodies data
   Astronomy is factual. Astrology is presented descriptively:
   what the tradition assigns, never what will happen to anyone. */

const BODIES_DATA = [

  {
    id: "sun",
    name: "Sun",
    glyph: "☉",
    cls: "luminary",
    oneLine: "The chart's centre — core identity, vitality, and the self being built.",
    plain: "The Sun is the star everything else orbits, and astrologers treat it the same way inside a chart. They read it as the core self — what a person is at their steadiest, rather than the face put on for a room. Its sign is the one most people mean when they say what sign they are.",
    deep: "A G2V main-sequence star holding 99.86% of the solar system's mass, fusing roughly 600 million tonnes of hydrogen every second. It rotates differentially — about 25 days at the equator, 35 near the poles — on an ~11-year magnetic cycle that reverses its poles each time. Its light reaches Earth in 8 minutes 20 seconds, so every chart is drawn from starlight already eight minutes old. Astrologically the core identity: what remains when nothing is being performed for anyone. Ruler of Leo in every scheme, ancient and modern, and the one body no system has ever demoted.",
    rules: ["Leo"],
    rulesTrad: ["Leo"],
    exalt: "Aries",
    detriment: ["Aquarius"],
    fall: ["Libra"],
    discovered: "Known since antiquity",
    cycle: "~1 year through the zodiac",
    cycleDays: 365.256,
    perSign: "about 30 days",
    speed: "fast",
    retro: "The Sun and Moon never appear to move backwards.",
    astronomy: [
      "A G2V main-sequence star, roughly 4.6 billion years old.",
      "Holds 99.86% of the solar system's mass.",
      "Fuses about 600 million tonnes of hydrogen every second.",
      "Rotates differentially: ~25 days at the equator, ~35 near the poles.",
      "Magnetic activity runs on an ~11-year cycle, with the poles reversing each time.",
      "Its light takes 8 minutes 20 seconds to reach Earth."
    ],
    keywords: ["Identity", "Vitality", "Purpose", "Ego", "Radiance"],
    inChart: "Every chart contains the Sun in exactly one sign and one house. Astrologers use that placement as the reference point the rest of the chart is read against, rather than as a description of events.",
    color: "#ffcf5c"
  },

  {
    id: "moon",
    name: "Moon",
    glyph: "☽",
    cls: "luminary",
    oneLine: "Mood, instinct, and the private inner weather beneath the surface.",
    plain: "The Moon changes shape faster than anything else in the sky, and astrologers read it as the changeable part of a person. It stands for feelings, habits, comfort, and what someone reaches for without thinking. Because it moves so quickly, two people born on the same day can have it in different signs.",
    deep: "Tidally locked to Earth, so one hemisphere has faced us for billions of years while the far side went unseen until Luna 3 photographed it in 1959. It completes a sidereal circuit in 27.32 days but a full cycle of phases in 29.53, the difference being Earth's own motion around the Sun. It recedes from us by about 3.8 centimetres a year, lengthening the terrestrial day by fractions of a second per century. The tradition reads it as interior weather — reflex, memory, appetite, the parts of a life that run without supervision. Sole ruler of Cancer, and the fastest-moving point in any chart.",
    rules: ["Cancer"],
    rulesTrad: ["Cancer"],
    exalt: "Taurus",
    detriment: ["Capricorn"],
    fall: ["Scorpio"],
    discovered: "Known since antiquity",
    cycle: "~27.3 days through the zodiac",
    cycleDays: 27.322,
    perSign: "about two and a half days",
    speed: "very fast",
    retro: "The Sun and Moon never appear to move backwards.",
    astronomy: [
      "Diameter 3,474 km — just over a quarter of Earth's.",
      "Tidally locked; the far side was first photographed by Luna 3 in 1959.",
      "Sidereal month 27.32 days; the cycle of phases takes 29.53 days.",
      "Recedes from Earth by about 3.8 cm per year.",
      "Its orbit is tilted about 5.1° to the ecliptic, which is why eclipses are not monthly.",
      "Surface gravity is roughly one sixth of Earth's."
    ],
    keywords: ["Emotion", "Instinct", "Memory", "Comfort", "Rhythm"],
    inChart: "The Moon's sign and house are read as the emotional baseline — the conditions under which someone is said to settle. Because it covers about 13° a day, an accurate birth time matters more for the Moon than for any other body.",
    color: "#d6dceb"
  },

  {
    id: "mercury",
    name: "Mercury",
    glyph: "☿",
    cls: "personal",
    oneLine: "How a person thinks, speaks, learns, and moves information around.",
    plain: "Mercury never strays far from the Sun in the sky, so it always lands in or beside the Sun sign. Astrologers read it as the mind at work — how someone thinks, phrases things, and takes information in. As the messenger it also covers what moves: speech, writing, errands, short journeys.",
    deep: "The smallest planet and the closest, held in a 3:2 spin-orbit resonance — three rotations for every two orbits — so a single solar day there spans two Mercurian years. Its orbit is the most eccentric of the planets, and the surplus precession of its perihelion, 43 arcseconds a century, resisted every Newtonian account until general relativity supplied one. Seen from Earth it never departs more than about 28° from the Sun, which is why it circles the zodiac in step with the Sun rather than in its own 88 days. The tradition assigns it the mind in motion: language, exchange, commerce, the crossing of thresholds. It rules Gemini and Virgo in both the classical and modern schemes, the only planet whose two signs no revision has touched.",
    rules: ["Gemini", "Virgo"],
    rulesTrad: ["Gemini", "Virgo"],
    exalt: "Virgo",
    detriment: ["Sagittarius", "Pisces"],
    fall: ["Pisces"],
    discovered: "Known since antiquity",
    cycle: "~1 year through the zodiac, tied to the Sun",
    cycleDays: 365.256,
    perSign: "roughly 2 to 4 weeks, varying with its speed",
    speed: "very fast",
    retro: "About 3 times a year, for roughly 3 weeks each time.",
    astronomy: [
      "Orbits the Sun in 87.97 days — the shortest year of any planet.",
      "Held in a 3:2 spin-orbit resonance: three rotations per two orbits.",
      "The smallest planet — smaller than the moons Ganymede and Titan.",
      "Surface temperatures swing from about −180 °C to 430 °C.",
      "Water ice survives in permanently shadowed craters at its poles.",
      "The extra precession of its perihelion, 43 arcseconds per century, was explained only by general relativity."
    ],
    keywords: ["Mind", "Language", "Curiosity", "Exchange", "Dexterity"],
    inChart: "Mercury falls in the Sun's sign or one adjacent to it in every chart, so astrologers read it as a modifier of the solar placement rather than an independent one. Its house is taken to show where attention naturally gathers.",
    color: "#7fd1b9"
  },

  {
    id: "venus",
    name: "Venus",
    glyph: "♀",
    cls: "personal",
    oneLine: "What a person finds beautiful, and how they relate and value.",
    plain: "Venus is the brightest thing in the sky after the Sun and Moon, and astrologers read it as the part of us drawn toward things. It covers attraction, taste, affection, money, and what feels worth having. Less about hunger than about pleasure — what makes a life feel good to be inside.",
    deep: "It rotates retrograde and so slowly that a Venusian day outlasts its 225-day year. Its surface sits near 465 °C beneath 92 bars of carbon dioxide, hot enough to melt lead, held there by a runaway greenhouse rather than by nearness to the Sun. Successive conjunctions with Earth trace a five-petalled figure across eight years — five synodic cycles against thirteen Venusian ones — and that harmonic geometry is the astronomical root of Venus's ancient link to beauty and proportion. The tradition assigns it value, attraction, and the terms on which one thing is exchanged for another. Ruler of Taurus by night and Libra by day in the classical scheme, and of both in the modern one.",
    rules: ["Taurus", "Libra"],
    rulesTrad: ["Taurus", "Libra"],
    exalt: "Pisces",
    detriment: ["Aries", "Scorpio"],
    fall: ["Virgo"],
    discovered: "Known since antiquity",
    cycle: "~1 year through the zodiac, tied to the Sun",
    cycleDays: 365.256,
    perSign: "roughly 3 to 5 weeks",
    speed: "fast",
    retro: "About every 18 months, for roughly 6 weeks.",
    astronomy: [
      "Rotates retrograde once every 243 days — longer than its 224.7-day year.",
      "Surface temperature near 465 °C, the hottest of any planet.",
      "Its atmosphere is 96% carbon dioxide at about 92 times Earth's surface pressure.",
      "It has no moons.",
      "The brightest planet in our sky, reaching magnitude −4.6.",
      "Five Earth–Venus conjunctions fall almost exactly within eight years, tracing a five-pointed figure."
    ],
    keywords: ["Attraction", "Value", "Harmony", "Pleasure", "Taste"],
    inChart: "Venus is never more than about 48° from the Sun, so it sits in the solar sign or within two of it. Astrologers read its sign for aesthetic and relational style and its house for where a sense of value is said to be invested.",
    color: "#f2a0c4"
  },

  {
    id: "mars",
    name: "Mars",
    glyph: "♂",
    cls: "personal",
    oneLine: "Drive, anger, and the way a person goes after what they want.",
    plain: "Mars is the planet astrologers connect with action. It stands for drive, appetite, competitiveness, and how someone handles conflict — charging in, waiting it out, or stepping around it. Where Venus is what a person is drawn to, Mars is what they do about it.",
    deep: "Half Earth's diameter, wrapped in a carbon dioxide atmosphere less than a hundredth as dense as ours, its colour the iron oxide lying across everything. It carries Olympus Mons at roughly 22 kilometres of relief and Valles Marineris, a canyon system running some 4,000 kilometres — neither with any terrestrial equal. Its day is 24 hours and 37 minutes and its axial tilt of 25° gives it seasons much like our own, stretched across a 687-day year. The tradition assigns it the will in its cutting form: assertion, appetite, severance, the decision to act. Ruler of Aries in every scheme and of Scorpio in the classical one, before Pluto was assigned there.",
    rules: ["Aries"],
    rulesTrad: ["Aries", "Scorpio"],
    exalt: "Capricorn",
    detriment: ["Libra", "Taurus"],
    fall: ["Cancer"],
    discovered: "Known since antiquity",
    cycle: "~1 year 11 months through the zodiac",
    cycleDays: 686.98,
    perSign: "about 6 to 7 weeks",
    speed: "medium",
    retro: "About every 26 months, for roughly 2 to 2 and a half months.",
    astronomy: [
      "A Martian year lasts 687 Earth days; a Martian day lasts 24 hours 37 minutes.",
      "Two small moons, Phobos and Deimos, probably captured asteroids.",
      "Olympus Mons rises about 22 km — the tallest volcano known in the solar system.",
      "Valles Marineris runs roughly 4,000 km along the equator.",
      "Its atmosphere is about 95% carbon dioxide at under 1% of Earth's surface pressure.",
      "Its red colour comes from iron oxide in the surface dust."
    ],
    keywords: ["Drive", "Courage", "Conflict", "Desire", "Action"],
    inChart: "Astrologers read Mars's sign as the style of a person's assertion and its house as the area where effort and friction are said to concentrate. The reading describes a disposition, not an outcome.",
    color: "#e0533d"
  },

  {
    id: "jupiter",
    name: "Jupiter",
    glyph: "♃",
    cls: "social",
    oneLine: "Growth, generosity, belief — the part of a chart that expands things.",
    plain: "Jupiter is the largest planet, and astrologers give it the largest job: growth. They read it as the urge to expand — through travel, study, belief, or simply wanting more. Classical texts call it the greater benefic, the planet said to make things easier.",
    deep: "Two and a half times the mass of every other planet combined, and the fastest spinner among them at 9 hours 55 minutes, quickly enough to flatten its poles visibly. The Great Red Spot is a high-pressure storm wider than Earth, under continuous observation for well over a century. The four moons Galileo resolved in 1610 were the first bodies confirmed to orbit something other than Earth, and Ganymede among them exceeds Mercury in size. The tradition assigns it increase, meaning, and the assumption that room is available — the greater benefic in classical terms. Ruler of Sagittarius in both schemes and of Pisces in the classical one.",
    rules: ["Sagittarius"],
    rulesTrad: ["Sagittarius", "Pisces"],
    exalt: "Cancer",
    detriment: ["Gemini", "Virgo"],
    fall: ["Capricorn"],
    discovered: "Known since antiquity",
    cycle: "~12 years through the zodiac",
    cycleDays: 4332.59,
    perSign: "about 1 year",
    speed: "medium",
    retro: "Once a year, for about 4 months.",
    astronomy: [
      "Two and a half times the mass of all the other planets combined.",
      "Rotates in 9 hours 55 minutes — the fastest of the planets, which visibly flattens it.",
      "The Great Red Spot is a storm wider than Earth.",
      "Its four largest moons were observed by Galileo in 1610.",
      "Ganymede is the largest moon in the solar system, bigger than Mercury.",
      "It orbits the Sun once every 11.86 years."
    ],
    keywords: ["Expansion", "Faith", "Abundance", "Wisdom", "Excess"],
    inChart: "Jupiter spends roughly a year in each sign, so everyone born within about twelve months shares that placement. Astrologers therefore treat its house as the more individual signal — the area where a chart is said to seek room.",
    color: "#b689f0"
  },

  {
    id: "saturn",
    name: "Saturn",
    glyph: "♄",
    cls: "social",
    oneLine: "Limits, structure, and the slow work of building something durable.",
    plain: "Saturn is the last planet visible without a telescope, which made it the ancient edge of the known sky. Astrologers read it as limits: time, rules, responsibility, and the effort a thing actually takes. Its reputation is harsh, but the tradition also treats it as what allows anything to last.",
    deep: "The least dense of the planets at 0.69 grams per cubic centimetre — light enough to float in a sufficiently large ocean. Its rings span some 280,000 kilometres yet run only tens of metres thick, almost pure water ice and geologically young. A persistent hexagonal jet stream circles its north pole, and its moon Titan holds a nitrogen atmosphere denser than Earth's above lakes of liquid methane. As the outermost planet visible to the unaided eye it marked the boundary of the classical cosmos, which is why the tradition assigns it limit, time, and consequence. Ruler of Capricorn in both schemes and of Aquarius before Uranus was placed there.",
    rules: ["Capricorn"],
    rulesTrad: ["Capricorn", "Aquarius"],
    exalt: "Libra",
    detriment: ["Cancer", "Leo"],
    fall: ["Aries"],
    discovered: "Known since antiquity",
    cycle: "~29.5 years through the zodiac",
    cycleDays: 10759.22,
    perSign: "about two and a half years",
    speed: "slow",
    retro: "Once a year, for about 4 and a half months.",
    astronomy: [
      "Mean density 0.69 g/cm³ — less than water.",
      "Its rings span about 280,000 km but are only tens of metres thick.",
      "The ring material is almost pure water ice.",
      "A hexagonal jet stream circles its north pole.",
      "Titan has a nitrogen atmosphere denser than Earth's, over lakes of liquid methane.",
      "It is the outermost planet visible without a telescope."
    ],
    keywords: ["Structure", "Limit", "Time", "Discipline", "Consequence"],
    inChart: "Saturn returns to its natal position at roughly ages 29 and 59, one of the tradition's most-cited cycles. Astrologers describe those returns as periods of restructuring rather than as specific events.",
    color: "#8a8f9e"
  },

  {
    id: "uranus",
    name: "Uranus",
    glyph: "♅",
    cls: "outer",
    oneLine: "Sudden change, invention, and the impulse to break a pattern.",
    plain: "Uranus was the first planet ever found with a telescope, and its discovery doubled the size of the known solar system overnight. Astrologers read it as disruption — the sudden turn, the invention, the refusal to do things the usual way. It moves slowly, so it is treated as marking a whole generation more than one person.",
    deep: "Found by William Herschel in March 1781, the first planet added to the sky since antiquity and the discovery that doubled the known radius of the solar system. It rolls on its side at an axial tilt near 98°, so each pole spends 42 years in unbroken sunlight and 42 in darkness. Its atmosphere records the coldest temperature measured on any planet, close to 49 kelvin, and its rings were detected in 1977 by watching a star wink out behind them. Voyager 2 remains the only spacecraft to have passed it, in 1986. The tradition assigns it rupture and reversal, and modern practice makes it ruler of Aquarius — a sign Saturn had held alone for two millennia.",
    rules: ["Aquarius"],
    rulesTrad: [],
    exalt: "",
    detriment: ["Leo"],
    fall: [],
    discovered: "1781, by William Herschel",
    cycle: "~84 years through the zodiac",
    cycleDays: 30688.5,
    perSign: "about 7 years",
    speed: "very slow",
    retro: "Once a year, for about 5 months.",
    astronomy: [
      "Discovered in March 1781 by William Herschel — the first planet found with a telescope.",
      "Axial tilt near 98°: it effectively orbits on its side.",
      "Each pole receives 42 years of continuous sunlight, then 42 of darkness.",
      "It holds the coldest atmospheric temperature measured on any planet, near 49 K.",
      "Its rings were discovered in 1977 during a stellar occultation.",
      "Voyager 2 is the only spacecraft to have visited, passing in 1986."
    ],
    keywords: ["Disruption", "Invention", "Freedom", "Awakening", "Deviation"],
    inChart: "Uranus occupies one sign for roughly seven years, so its sign is shared across an age cohort. Astrologers read its house and its aspects as the part of the placement specific to a single chart.",
    color: "#4fd0e3"
  },

  {
    id: "neptune",
    name: "Neptune",
    glyph: "♆",
    cls: "outer",
    oneLine: "Imagination, dreams, and the blurring of edges between things.",
    plain: "Neptune was found by mathematics before anyone went looking — its position was calculated from wobbles in the orbit of Uranus. Astrologers read it as everything without hard edges: dreams, imagination, faith, illusion, escape. Like Uranus it moves slowly, so its sign describes a generation.",
    deep: "Located by prediction rather than survey: Urbain Le Verrier computed where the perturbations of Uranus demanded a planet, and Johann Galle found it within a degree of that point on the night of 23 September 1846. It radiates roughly 2.6 times the energy it receives from the Sun, driving the fastest winds measured anywhere in the solar system. Its largest moon, Triton, orbits backwards and is almost certainly a captured Kuiper Belt object, venting nitrogen from a surface near 38 kelvin. It completed its first full circuit since discovery only in 2011. The tradition assigns it dissolution — the softening of outline in both its visionary and its deceptive registers — and modern practice makes it ruler of Pisces.",
    rules: ["Pisces"],
    rulesTrad: [],
    exalt: "",
    detriment: ["Virgo"],
    fall: [],
    discovered: "1846, by Johann Galle",
    cycle: "~165 years through the zodiac",
    cycleDays: 60195,
    perSign: "about 14 years",
    speed: "very slow",
    retro: "Once a year, for about 5 months.",
    astronomy: [
      "Predicted mathematically by Le Verrier, then observed by Galle on 23 September 1846.",
      "It orbits the Sun once every 164.8 years.",
      "It radiates about 2.6 times the energy it receives from the Sun.",
      "Its winds are the fastest measured in the solar system.",
      "Triton orbits backwards and is likely a captured Kuiper Belt object.",
      "It completed its first orbit since discovery in 2011."
    ],
    keywords: ["Imagination", "Dissolution", "Compassion", "Illusion", "Transcendence"],
    inChart: "Neptune stays in one sign for roughly fourteen years, so astrologers treat that sign as a generational marker. Anything read as individual comes from its house placement and the aspects it makes.",
    color: "#4f7fe0"
  },

  {
    id: "pluto",
    name: "Pluto",
    glyph: "♇",
    cls: "outer",
    oneLine: "Deep change — what is buried, what holds power, what transforms.",
    plain: "Pluto is small, remote, and no longer officially a planet, but astrologers kept it. They read it as depth and transformation: power, obsession, what stays hidden, and things that end so that something else can begin. It is the slowest of the commonly used bodies.",
    deep: "Found by Clyde Tombaugh in February 1930 by blinking photographic plates against one another, and reclassified as a dwarf planet in 2006 once comparable bodies turned up beyond it. Its orbit is eccentric and tilted 17° to the ecliptic, carrying it inside Neptune's path between 1979 and 1999 while a 3:2 resonance guarantees the two never meet. Charon exceeds half its diameter, so the pair swing around a barycentre standing in open space above Pluto's surface. New Horizons passed in July 2015 and returned Sputnik Planitia, a convecting glacier of nitrogen ice carrying no impact craters at all. The tradition assigns it what operates beneath the visible — power, compulsion, irreversible change — as modern ruler of Scorpio.",
    rules: ["Scorpio"],
    rulesTrad: [],
    exalt: "",
    detriment: ["Taurus"],
    fall: [],
    discovered: "1930, by Clyde Tombaugh",
    cycle: "~248 years through the zodiac",
    cycleDays: 90560,
    perSign: "between about 12 and 31 years, depending on the sign",
    speed: "very slow",
    retro: "Once a year, for about 5 to 6 months.",
    astronomy: [
      "Discovered in February 1930 by Clyde Tombaugh at Lowell Observatory.",
      "Reclassified by the IAU as a dwarf planet in 2006.",
      "Its orbit is tilted 17° and eccentric enough to bring it inside Neptune's, as it was from 1979 to 1999.",
      "A 3:2 orbital resonance with Neptune means the two can never collide.",
      "Five known moons; Charon is more than half Pluto's diameter.",
      "New Horizons flew past in July 2015 and imaged Sputnik Planitia, a glacier of nitrogen ice."
    ],
    keywords: ["Transformation", "Power", "Depth", "Obsession", "Regeneration"],
    inChart: "Pluto's eccentric orbit takes it through some signs in twelve years and others in thirty, so cohort sizes vary sharply. Astrologers read the house it occupies as the area a chart is said to be reworked through.",
    color: "#74468a"
  },

  {
    id: "chiron",
    name: "Chiron",
    glyph: "⚷",
    cls: "minor",
    oneLine: "The sore spot a person keeps returning to, and what it teaches.",
    plain: "Chiron is a small icy body orbiting between Saturn and Uranus, discovered in 1977. Astrologers read it as an old tender place — something that never fully resolves but can turn into skill or empathy. It has no accepted rulership at all, though various modern schools associate it loosely with Virgo or Sagittarius.",
    deep: "Discovered by Charles Kowal in November 1977, the first of the centaurs — a class of bodies on unstable orbits among the giant planets. It behaves as both asteroid and comet, and is catalogued twice for that reason, as 2060 Chiron and as 95P/Chiron, after a coma appeared near perihelion. Its path crosses inside Saturn's orbit and reaches out toward Uranus, so it belongs cleanly to neither, and gravitational perturbation gives it a dynamical lifetime of perhaps a million years. Its eccentricity means it can clear one sign in little more than a year and take close to eight in another. The interpretive tradition assembled around it since 1977 assigns it the injury that instructs; no classical rulership, exaltation, or fall attaches to it.",
    rules: [],
    rulesTrad: [],
    exalt: "",
    detriment: [],
    fall: [],
    discovered: "1977, by Charles Kowal",
    cycle: "~50 years through the zodiac",
    cycleDays: 18416,
    perSign: "from about 1.5 years to about 8, depending on the sign",
    speed: "slow",
    retro: "Once a year, for about 5 months.",
    astronomy: [
      "Discovered in November 1977 by Charles Kowal.",
      "The first known centaur — a body orbiting between Saturn and Uranus.",
      "Classified as both asteroid and comet: 2060 Chiron and 95P/Chiron.",
      "Roughly 200 km across.",
      "Its orbit is unstable, with a dynamical lifetime on the order of a million years.",
      "Stellar occultations since 2011 point to rings or a debris structure around it."
    ],
    keywords: ["Wound", "Healing", "Mentorship", "Vulnerability", "Bridge"],
    inChart: "Chiron carries no dignities, so astrologers read it purely by sign, house, and aspect. Its placement is described as a recurring sensitivity rather than a fixed trait.",
    color: "#b5724a"
  },

  {
    id: "ceres",
    name: "Ceres",
    glyph: "⚳",
    cls: "minor",
    oneLine: "Nurture, food, and the cycle of holding on and letting go.",
    plain: "Ceres is the largest object in the asteroid belt and now counts as a dwarf planet. Astrologers read it as care in its practical form: feeding, tending, and the harder edge of that — separation and loss. It has no accepted rulership, though modern schools often associate it with Cancer, Taurus, or Virgo.",
    deep: "Discovered by Giuseppe Piazzi on the first night of the nineteenth century, catalogued as a planet for some fifty years, demoted to asteroid, then reclassified once more in 2006 as a dwarf planet — the only one inside Neptune's orbit. At roughly 940 kilometres across it accounts for around a quarter of the asteroid belt's total mass. Dawn orbited it from 2015 to 2018 and resolved the bright deposits of Occator crater as sodium carbonate left by brine reaching the surface, evidence of liquid water below. Named for the Roman goddess of grain, and the interpretive tradition assigns it sustenance and its withdrawal — the figure who feeds and the figure who loses. No classical dignities attach to it.",
    rules: [],
    rulesTrad: [],
    exalt: "",
    detriment: [],
    fall: [],
    discovered: "1801, by Giuseppe Piazzi",
    cycle: "~4.6 years through the zodiac",
    cycleDays: 1681.6,
    perSign: "about 4 to 5 months on average",
    speed: "medium",
    retro: "About every 15 months, for roughly 3 months.",
    astronomy: [
      "Discovered on 1 January 1801 by Giuseppe Piazzi in Palermo.",
      "The largest object in the asteroid belt, about 940 km across.",
      "Holds roughly a quarter of the belt's total mass.",
      "Counted as a planet for about fifty years before being reclassified as an asteroid.",
      "Named a dwarf planet in 2006 — the only one inside Neptune's orbit.",
      "Dawn orbited it from 2015 to 2018; Occator's bright deposits are sodium carbonate from subsurface brine."
    ],
    keywords: ["Nurture", "Sustenance", "Loss", "Cycles", "Care"],
    inChart: "Astrologers place Ceres by sign and house like any other body and read it for how care is said to be given and received. It carries no dignity scheme and is optional in most systems.",
    color: "#6fae63"
  },

  {
    id: "pallas",
    name: "Pallas",
    glyph: "⚴",
    cls: "minor",
    oneLine: "Pattern recognition, strategy, and solving problems by design.",
    plain: "Pallas was the second asteroid ever found, named after Pallas Athena. Astrologers read it as the strategic mind — spotting patterns, planning several moves ahead, resolving things by design rather than by force. Like the other asteroids it has no accepted rulership, though it is often associated with Aquarius, Libra, or Virgo.",
    deep: "Found by Heinrich Olbers in March 1802, the second asteroid discovered and the third most massive, near 512 kilometres in mean diameter. Its orbit is inclined almost 35° to the ecliptic — extreme for a body of that size — which lifts it clear of the belt's main plane and makes it costly to reach. The element palladium, isolated the following year, was named after it. It carries Athena's name in her aspect of strategy and craft rather than of combat, and the interpretive tradition built up since the 1970s assigns it pattern recognition, mediation, and the intelligence that resolves instead of striking. No classical rulership or dignity attaches to it.",
    rules: [],
    rulesTrad: [],
    exalt: "",
    detriment: [],
    fall: [],
    discovered: "1802, by Heinrich Olbers",
    cycle: "~4.6 years through the zodiac",
    cycleDays: 1686,
    perSign: "about 4 to 5 months on average",
    speed: "medium",
    retro: "About every 15 to 16 months, for roughly 3 months.",
    astronomy: [
      "Discovered in March 1802 by Heinrich Olbers — the second asteroid found.",
      "The third most massive asteroid, about 512 km in mean diameter.",
      "Its orbit is inclined almost 35° to the ecliptic, unusually steep for a large asteroid.",
      "The element palladium, isolated in 1803, was named after it.",
      "No spacecraft has yet visited it."
    ],
    keywords: ["Strategy", "Pattern", "Craft", "Mediation", "Perception"],
    inChart: "Astrologers read Pallas by sign, house, and aspect for a described style of problem-solving. It has no dignities and does not appear in every chart system.",
    color: "#5fa8c9"
  },

  {
    id: "juno",
    name: "Juno",
    glyph: "⚵",
    cls: "minor",
    oneLine: "Partnership, commitment, and the terms two people agree on.",
    plain: "Juno was the third asteroid discovered, named for the Roman goddess of marriage. Astrologers read it as what someone looks for in a committed partnership and what they count as fair inside one. It has no accepted rulership, though modern schools often associate it with Libra or Scorpio.",
    deep: "Discovered by Karl Harding in September 1804 and briefly counted a planet alongside Ceres, Pallas, and Vesta, before the true population of the belt made that untenable. One of the largest stony S-type asteroids at roughly 250 kilometres across, it follows a markedly eccentric path that swings its distance from the Sun by nearly a third over each 4.4-year circuit. It bears the name of the goddess whose domain was marriage and its breaches — her husband's above all — and the interpretive tradition assigns it the contract between equals: what is promised, what is expected, and what follows when the terms fail. No classical dignities attach to it.",
    rules: [],
    rulesTrad: [],
    exalt: "",
    detriment: [],
    fall: [],
    discovered: "1804, by Karl Harding",
    cycle: "~4.4 years through the zodiac",
    cycleDays: 1594,
    perSign: "about 4 months on average",
    speed: "medium",
    retro: "About every 16 months, for roughly 3 months.",
    astronomy: [
      "Discovered on 1 September 1804 by Karl Harding — the third asteroid found.",
      "About 250 km across, one of the largest stony S-type asteroids.",
      "Orbits the Sun in roughly 4.4 years.",
      "Its orbit is notably eccentric, varying its distance from the Sun by about a third.",
      "It was classed as a planet for several decades after discovery."
    ],
    keywords: ["Commitment", "Partnership", "Equity", "Loyalty", "Contract"],
    inChart: "Astrologers read Juno's sign and house as a description of what a person is said to seek in long-term partnership. It is a symbolic reading and makes no claim about any actual relationship.",
    color: "#cf7f9e"
  },

  {
    id: "vesta",
    name: "Vesta",
    glyph: "⚶",
    cls: "minor",
    oneLine: "Focus, devotion, and keeping one thing sacred above the rest.",
    plain: "Vesta is the brightest asteroid and can occasionally be seen without a telescope. Astrologers read it as concentrated devotion — the work, practice, or cause someone gives themselves to, sometimes at the cost of everything else. It has no accepted rulership, though it is often associated with Virgo or Scorpio.",
    deep: "Discovered by Heinrich Olbers in March 1807 and the brightest asteroid in the sky, reaching naked-eye visibility at favourable oppositions. It is a differentiated protoplanet with an iron core rather than a rubble pile — in effect a planet that stopped forming — and the Rheasilvia basin covers most of its southern hemisphere, having excavated material that still arrives on Earth as the HED meteorites. Dawn orbited it through 2011 and 2012 before leaving for Ceres, the first spacecraft to depart orbit around one body for another. It carries the name of the goddess of the hearth, whose flame the Vestals were bound to keep alight, and the interpretive tradition assigns it focus held to the exclusion of other things. No classical dignities attach to it.",
    rules: [],
    rulesTrad: [],
    exalt: "",
    detriment: [],
    fall: [],
    discovered: "1807, by Heinrich Olbers",
    cycle: "~3.6 years through the zodiac",
    cycleDays: 1325.4,
    perSign: "about 3 to 4 months on average",
    speed: "medium",
    retro: "About every 17 months, for roughly 3 months.",
    astronomy: [
      "Discovered in March 1807 by Heinrich Olbers.",
      "The brightest asteroid, visible to the unaided eye at its best oppositions.",
      "About 525 km across and the second most massive asteroid.",
      "A differentiated protoplanet with an iron core.",
      "The Rheasilvia impact basin covers most of its southern hemisphere.",
      "The HED meteorites found on Earth were blasted off Vesta."
    ],
    keywords: ["Devotion", "Focus", "Discipline", "Service", "Sanctity"],
    inChart: "Astrologers read Vesta's sign and house for where sustained, narrowed attention is said to gather. It carries no dignities and is not used by every school.",
    color: "#f0b429"
  },

  {
    id: "eris",
    name: "Eris",
    glyph: "⯰",
    cls: "minor",
    oneLine: "Discord, exclusion, and the thing nobody wanted said aloud.",
    plain: "Eris is a distant dwarf planet roughly the size of Pluto, identified in 2005 — and it is the reason Pluto lost its planet status. Astrologers read it as disruption from outside: what gets left out, and the conflict that follows when it refuses to stay quiet. It is very new to astrology and has no accepted rulership, though some link it to Aries.",
    deep: "Imaged in 2003 and identified in January 2005 by Mike Brown, Chad Trujillo, and David Rabinowitz, its existence obliged the IAU to define the word planet, and the definition that emerged excluded Pluto. Slightly smaller than Pluto in diameter yet about 27% more massive, it follows a highly eccentric orbit inclined 44° to the ecliptic and reaching roughly 97 astronomical units from the Sun. Its surface of methane frost is among the most reflective in the solar system, and its single known moon, Dysnomia, takes the name of the goddess's daughter. Named for the deity who threw the golden apple that started the Trojan War, and the interpretive tradition forming since 2005 reads it as the excluded party and the disorder that exclusion produces. Discovered far too recently to carry any dignity scheme.",
    rules: [],
    rulesTrad: [],
    exalt: "",
    detriment: [],
    fall: [],
    discovered: "2005, by Mike Brown, Chad Trujillo and David Rabinowitz",
    cycle: "~560 years through the zodiac",
    cycleDays: 204175,
    perSign: "several decades, and well over a century in some signs",
    speed: "very slow",
    retro: "Once a year, for about 5 months.",
    astronomy: [
      "Imaged in 2003 and identified in January 2005 by Brown, Trujillo and Rabinowitz.",
      "Its discovery prompted the IAU's 2006 definition of a planet, which reclassified Pluto.",
      "Slightly smaller than Pluto in diameter but about 27% more massive.",
      "Its orbit is inclined 44° and highly eccentric, reaching about 97 AU from the Sun.",
      "Its methane-frost surface is among the most reflective in the solar system.",
      "It has one known moon, Dysnomia."
    ],
    keywords: ["Discord", "Exclusion", "Defiance", "Reckoning", "Disruption"],
    inChart: "Eris has spent roughly a century in Aries, so nearly everyone now living shares its sign. Astrologers who use it read the house and the aspects, since the sign carries no individual distinction.",
    color: "#9c3f5c"
  }

];
