/* Cosmic Atlas — the twelve houses.
   Houses are the twelve slices of sky measured from the horizon at a given
   moment and place. Signs describe style; houses describe the area of life
   a tradition assigns that style to. Descriptive only — nothing here
   forecasts anything. */

const HOUSES_DATA = [
  {
    n: 1,
    name: "The First House",
    title: "Self & Identity",
    glyph: "I",
    naturalSign: "Aries",
    angular: "angular",
    oneLine: "The house of the self — your body, your look, your opening move.",
    plain: "This is the house of you as a physical, visible thing. It covers how you come across before you have said a word, what you look like, and the way you tend to begin something new. Astrologers treat it as the doorway to the whole chart.",
    deep: "The first house begins at the Ascendant, the degree of the zodiac climbing over the eastern horizon at the moment of birth — the exact seam where sky meets earth. Traditionally it is read as the body itself: colouring, carriage, vitality, and the manner in which a life announces itself before anything is said. Because it opens the circle, every other house is counted forward from its edge. The tradition treats it less as personality than as aperture, the shape of the opening through which everything else is met.",
    covers: ["Appearance", "First impressions", "The physical body", "How you start things", "Temperament"],
    question: "Who am I when I walk into the room?",
    cusp: "The cusp of the first house is the Ascendant, also called the Rising sign — the zodiac degree coming up over the eastern horizon at the moment of birth.",
    color: "#ff5f45"
  },
  {
    n: 2,
    name: "The Second House",
    title: "Money & Values",
    glyph: "II",
    naturalSign: "Taurus",
    angular: "succedent",
    oneLine: "The house of what you own, earn, and quietly consider valuable.",
    plain: "This house covers money, belongings, and everything you can call yours. It also covers what you value — the things you would not trade away. Astrologers read it for how a person builds and holds resources.",
    deep: "The second house answers the fact of arrival with the question of sustenance. Older texts call it substance, and hand it livestock, grain and coin — anything that can be counted, held, and lost. Its natural sign is Taurus, fixed earth, and the house inherits that slowness: value here accumulates rather than arrives. The tradition extends the idea inward as well, treating what a person prizes as inseparable from what a person keeps.",
    covers: ["Income", "Possessions", "Personal values", "Self-worth", "The senses", "Resources"],
    question: "What is mine, and what is it worth to me?",
    cusp: "",
    color: "#3fdc8b"
  },
  {
    n: 3,
    name: "The Third House",
    title: "Mind & Communication",
    glyph: "III",
    naturalSign: "Gemini",
    angular: "cadent",
    oneLine: "The house of talking, learning, siblings and short local trips.",
    plain: "This is the everyday mind: conversation, texts, reading, and the way you explain things. It also covers brothers and sisters, neighbours, and journeys short enough to make twice in a day. Think of it as your local world.",
    deep: "The third house is the near world — the streets walked without thinking, the siblings raised in the same rooms, the errands and messages that fill an ordinary week. Classical sources name it the house of the goddess and pair it with the Moon's swift local motion. Its concern is not truth but circulation: how information moves, how it is phrased, how fast it travels. Gemini's mutable air gives the house its restlessness and its taste for the unfinished sentence.",
    covers: ["Conversation", "Writing and messages", "Siblings", "Neighbours", "Short journeys", "Early learning"],
    question: "How do I take things in, and how do I pass them on?",
    cusp: "",
    color: "#ffd35e"
  },
  {
    n: 4,
    name: "The Fourth House",
    title: "Home & Roots",
    glyph: "IV",
    naturalSign: "Cancer",
    angular: "angular",
    oneLine: "The house of home, family, ancestry and private life.",
    plain: "This house covers where you live and where you came from. It holds family, childhood, and the parts of life nobody outside the household sees. It is the base of the chart, the ground everything else stands on.",
    deep: "The fourth house sits at the very bottom of the chart, at the Imum Coeli — the lowest point, the invisible midnight beneath the earth at the moment of birth. It is the foundation, and the tradition reads it for lineage, dwelling, and the interior that the public never enters. Older texts also give it the end of the matter: the grave, the inheritance, the final condition of things. Cancer's cardinal water makes it a house of shelter that is always, at the same time, a house of memory.",
    covers: ["Home", "Family", "Ancestry", "Childhood", "Private life", "Endings and foundations"],
    question: "Where do I come from, and where do I feel safe?",
    cusp: "The cusp of the fourth house is the IC, or Imum Coeli — Latin for the lowest heaven, the point directly opposite the Midheaven.",
    color: "#4fb6ff"
  },
  {
    n: 5,
    name: "The Fifth House",
    title: "Creativity & Play",
    glyph: "V",
    naturalSign: "Leo",
    angular: "succedent",
    oneLine: "The house of play, romance, children and making things for fun.",
    plain: "This house covers everything done for its own pleasure: art, games, flirting, sport, performance. It also traditionally covers children and creative work of any kind. It is the part of life that does not have to justify itself.",
    deep: "The fifth house is the surplus — what gets made once survival has been secured. Older astrology calls it Good Fortune and assigns it children, games, wagers, and pleasures that serve nothing beyond themselves. Its natural rulers are Leo and, by extension, the Sun, so the house runs on the logic of radiance: something is emitted, and the emitting is its own reward. Creation and procreation are treated as one gesture here, the self extended into something that did not exist before.",
    covers: ["Creative work", "Romance and flirtation", "Children", "Games and risk", "Performance", "Pleasure"],
    question: "What do I make simply because I enjoy making it?",
    cusp: "",
    color: "#ff5f45"
  },
  {
    n: 6,
    name: "The Sixth House",
    title: "Work & Health",
    glyph: "VI",
    naturalSign: "Virgo",
    angular: "cadent",
    oneLine: "The house of daily work, routine, health and useful habits.",
    plain: "This house covers the ordinary running of life: the job rather than the career, the chores, the exercise, the diet, the repeat. It also covers health, colleagues, and small animals. Nothing glamorous, everything necessary.",
    deep: "The sixth house is maintenance — the body's repairs, the labour that repeats, the small creatures and small tasks kept alive by attention. Traditional texts name it Bad Fortune and pair it with sickness and servitude, a fair reflection of how little dignity ancient astrology granted to routine. Later practice reads it more generously, as craft: the slow discipline by which raw ability hardens into skill. Virgo's mutable earth suits it exactly, being the sign concerned with sorting, correcting, and finishing.",
    covers: ["Daily routine", "Work and craft", "Health and the body", "Service to others", "Colleagues", "Pets"],
    question: "What do I do with an ordinary Tuesday?",
    cusp: "",
    color: "#3fdc8b"
  },
  {
    n: 7,
    name: "The Seventh House",
    title: "Partnership & Others",
    glyph: "VII",
    naturalSign: "Libra",
    angular: "angular",
    oneLine: "The house of one-to-one relationships — partners, allies, opponents.",
    plain: "This house covers the other person: marriage, close partnership, business partners, and formal agreements. Older astrology also puts open rivals here, on the logic that you face them directly too. It sits exactly opposite the first house.",
    deep: "The seventh house begins at the Descendant, the degree setting in the west while the Ascendant rises in the east — the chart's exact opposite pole. It governs the encountered other: spouses, contracted partners, and, in older texts, declared enemies, on the reasoning that both are met face to face. Libra's cardinal air supplies the vocabulary of balance, negotiation, and the terms on which two parties agree to meet. The tradition reads it as the mirror in which whatever the first house cannot see in itself becomes visible.",
    covers: ["Marriage and partnership", "Business partners", "Contracts", "Open rivals", "Negotiation", "Close collaboration"],
    question: "Who do I meet face to face, and what happens when I do?",
    cusp: "The cusp of the seventh house is the Descendant — the zodiac degree setting on the western horizon, directly opposite the Ascendant.",
    color: "#ffd35e"
  },
  {
    n: 8,
    name: "The Eighth House",
    title: "Shared Resources & Depth",
    glyph: "VIII",
    naturalSign: "Scorpio",
    angular: "succedent",
    oneLine: "The house of joint money, deep bonds, loss and transformation.",
    plain: "This house covers what two people hold together: joint accounts, debts, loans, inheritance, taxes. It also covers intimacy, secrets, and the big irreversible changes — including death, in the older texts. It is the second house shared rather than owned.",
    deep: "The eighth house is what belongs to two people at once and to neither alone — dowries, debts, legacies, the estate of the dead. Classical astrology names it plainly as Death, and places it among the houses that cannot see the Ascendant. Its natural sign is Scorpio, fixed water, and the house keeps that sign's habit of holding matters below the surface until pressure forces them up. Later traditions read it psychologically, as the territory of what is shared, surrendered, or altered by contact with another.",
    covers: ["Joint finances", "Debt and inheritance", "Intimacy", "Secrets", "Loss", "Transformation"],
    question: "What do I share, and what changes me when I do?",
    cusp: "",
    color: "#4fb6ff"
  },
  {
    n: 9,
    name: "The Ninth House",
    title: "Belief & Distance",
    glyph: "IX",
    naturalSign: "Sagittarius",
    angular: "cadent",
    oneLine: "The house of long travel, big ideas, study and belief.",
    plain: "This house covers everything far away: foreign countries, other languages, university, law, religion and philosophy. It is where facts get built into a bigger picture. If the third house is the neighbourhood, this is the horizon.",
    deep: "The ninth house is the far world: long journeys, foreign tongues, law, doctrine, prophecy, and the university. Ancient sources name it God, and associate it with dreams and oracles — knowledge arriving from outside the ordinary channels of the third. Where the third gathers facts, the ninth arranges them into a system that claims to explain something. Sagittarius's mutable fire supplies the appetite for horizon, and the willingness to travel toward a meaning not yet confirmed.",
    covers: ["Long-distance travel", "Higher education", "Philosophy and religion", "Law", "Foreign cultures", "Publishing"],
    question: "What do I believe, and how far will I go to test it?",
    cusp: "",
    color: "#ff5f45"
  },
  {
    n: 10,
    name: "The Tenth House",
    title: "Career & Reputation",
    glyph: "X",
    naturalSign: "Capricorn",
    angular: "angular",
    oneLine: "The house of career, public standing and what you are known for.",
    plain: "This house covers your work in the world: your job title, your reputation, your ambitions, the people in authority above you. It is the most visible part of the chart. It sits directly opposite the fourth house of home.",
    deep: "The tenth house culminates at the Midheaven, the highest point the ecliptic reaches at the moment of birth — noon on the chart's private clock. It is the most exposed house, read for vocation, standing, and whatever a life is known for by people who will never meet it. Capricorn's cardinal earth governs it naturally, lending a slow structural ambition that treats a career as something built rather than received. Opposite the fourth, it is the public face of the same axis whose root is home.",
    covers: ["Career", "Reputation", "Authority figures", "Ambition", "Public role", "Legacy"],
    question: "What am I known for when I am not in the room?",
    cusp: "The cusp of the tenth house is the Midheaven, or MC (Medium Coeli) — the highest point the ecliptic reaches over the birthplace at that moment.",
    color: "#3fdc8b"
  },
  {
    n: 11,
    name: "The Eleventh House",
    title: "Friends & Community",
    glyph: "XI",
    naturalSign: "Aquarius",
    angular: "succedent",
    oneLine: "The house of friends, groups, networks and long-range hopes.",
    plain: "This house covers the people you choose rather than the people you are born to: friends, teams, clubs, causes, online communities. It also covers what you hope for. It is the group version of the fifth house's fun.",
    deep: "The eleventh house is the company kept by choice rather than blood — allies, guilds, patrons, and the loose federation of people who want the same thing. Classical astrology calls it Good Spirit and counts it fortunate, since it follows the Midheaven and shares in that elevation. Aquarius's fixed air makes it the house of the group as an idea: a network, a cause, a future held in common. It also holds hopes, which the tradition treats as a kind of possession — the not-yet, owned in advance.",
    covers: ["Friendships", "Groups and teams", "Networks", "Causes and communities", "Hopes and wishes", "Allies"],
    question: "Who are my people, and what are we aiming at together?",
    cusp: "",
    color: "#ffd35e"
  },
  {
    n: 12,
    name: "The Twelfth House",
    title: "Solitude & The Unseen",
    glyph: "XII",
    naturalSign: "Pisces",
    angular: "cadent",
    oneLine: "The house of solitude, hidden things, rest and letting go.",
    plain: "This house covers everything that happens out of sight: sleep, dreams, retreat, private grief, time spent alone. It also covers hospitals, prisons and monasteries — places set apart from ordinary life. It is the last house before the chart begins again.",
    deep: "The twelfth house is the last before the Ascendant, lying just below the eastern horizon in the dark immediately preceding sunrise. Ancient sources name it Bad Spirit and fill it with confinement, exile, hidden enemies, and the institutions that keep people out of view. Pisces's mutable water dissolves boundaries here, and the house has always been read as the place where the separate self thins — through sleep, retreat, devotion, or undoing. It closes the circle by surrendering whatever the first house is about to claim as an individual.",
    covers: ["Solitude", "Dreams and the unconscious", "Hidden matters", "Rest and retreat", "Institutions", "Endings"],
    question: "What do I carry that nobody sees?",
    cusp: "",
    color: "#4fb6ff"
  }
];
