/* Cosmic Atlas — "Sky & Story: where the zodiac came from"
   Ordered content blocks for the history explainer.
   kinds: "chapter" | "fact" | "compare" | "timeline" | "note"
*/
const HISTORY = [

  {
    id: "origins",
    kind: "chapter",
    title: "Before anyone wrote it down, people watched the sky",
    plain: "For most of human history the night sky was the most reliable thing anyone had. It kept time. It told you when to plant, when the river would rise, when the year had turned. Scribes in Mesopotamia — the region around the Tigris and Euphrates, in what is now Iraq — began writing down what they saw, night after night, for centuries. That habit of careful record-keeping is where the zodiac begins.\n\nThe first thing they noticed is that the Sun does not wander anywhere it likes. Over a year it traces one narrow path around the sky, always the same path. Astronomers call that path the ecliptic. The Moon and the visible planets stay close to it too, never straying far above or below. So the whole interesting part of the sky — the part where things move — is a band, not a dome. The zodiac is that band.\n\nWhy split it into twelve? Because the Moon runs through its cycle of phases about twelve times in the time the Sun takes to go around once. Twelve is what the sky handed them. And because Babylonian mathematics counted in sixties, the circle got 360 degrees — a number that divides cleanly by 12, giving each slice a tidy 30°. That is not mysticism. That is arithmetic done by people who liked round numbers and had a base-60 number system.\n\nBy roughly the start of the first millennium BCE this had been organised into a proper reference work. MUL.APIN — the name means simply the Plough Star, after the first constellation it lists — is a catalogue of stars, their rising and setting dates, and the path of the Sun and planets among them. It is a piece of astronomy: a working almanac, not a book of fortunes.",
    deep: "The very oldest Mesopotamian sky records are omen texts rather than star catalogues. The Venus tablet of Ammisaduqa records the risings and settings of Venus over a 21-year period, from around the 17th century BCE, and pairs them with statements about the fate of the kingdom. Note the scale: the omens are about the state, the harvest, the king. Personal astrology — a chart cast for an ordinary individual — is a much later invention, and the earliest surviving examples date to around 410 BCE.\n\nThe division into twelve equal 30° signs, as opposed to twelve unequal constellations, seems to have settled in Babylon during the 5th century BCE. This was a genuine technical advance. Constellations are ragged; equal signs are a coordinate system. Once the ecliptic was ruled off into equal parts, positions could be recorded, arithmetic could be done on them, and future positions could be predicted with tables. Babylonian astronomers became extremely good at this, centuries before anyone had a physical model of what the planets were doing or why.",
    aside: "The zodiac started life as a measuring tape for the sky, not a personality test."
  },

  {
    id: "timeline",
    kind: "timeline",
    title: "Three thousand years, in twelve steps",
    plain: "The zodiac has been handed from culture to culture for about three thousand years, and every culture changed it a little. Below is the short version. Dates before the common era are approximate — where historians argue over a decade or a century, this list uses a century.\n\nOne pattern is worth watching as you scroll: for most of this story, astronomy and astrology are the same job. The person calculating where Mars would be next spring and the person interpreting what Mars meant were usually the same person, often the same paid court official. They only separated recently.",
    deep: "Transmission was rarely a clean handoff. Ideas moved with traders, translators, refugees and conquering armies, and they mutated at every step. The Greeks took Babylonian mathematical astronomy and grafted on their own philosophy of the four elements. Persian and Arabic scholars preserved the Greek material through centuries when Europe had lost it, then added a great deal of their own observation and technique. Latin Europe got much of its classical inheritance back second-hand, translated out of Arabic, three or four languages downstream from where it started. Indian astronomy exchanged with the Hellenistic world in both directions and developed the parallel sidereal tradition that Jyotiṣa still uses today.",
    aside: "",
    events: [
      { year: "c. 1000 BCE", what: "MUL.APIN is compiled: a systematic catalogue of stars, their rising dates, and the road the Sun and planets travel.", where: "Babylon" },
      { year: "c. 5th century BCE", what: "The ecliptic is ruled off into twelve equal 30° signs — a coordinate system rather than a set of star pictures.", where: "Babylon" },
      { year: "c. 410 BCE", what: "The earliest known birth charts are written on clay: planetary positions recorded for the day a particular child was born.", where: "Babylon" },
      { year: "c. 3rd–1st century BCE", what: "Greek-speaking scholars absorb Babylonian planetary mathematics and fuse it with Greek geometry and four-element philosophy.", where: "Hellenistic Egypt & Greece" },
      { year: "2nd century CE", what: "Ptolemy writes the Almagest, the definitive mathematical astronomy of the ancient world, and the Tetrabiblos, which sets out astrological doctrine. Both are copied for over a thousand years.", where: "Alexandria" },
      { year: "9th century CE", what: "Greek and Persian works are translated into Arabic and heavily extended. Scholars such as Abū Maʿshar write treatises that later become European standards.", where: "Baghdad" },
      { year: "12th century CE", what: "Arabic texts are translated into Latin, returning Ptolemy and much else to Europe. Astrology arrives packaged together with trigonometry and observational astronomy.", where: "Toledo, Iberia" },
      { year: "13th–16th century CE", what: "Astrology is taught in universities and practised at courts, often as a branch of medicine. Kings, popes and physicians keep astrologers on staff.", where: "Europe" },
      { year: "17th–18th century CE", what: "After Copernicus (1543) and Galileo's telescope (1610), Newtonian gravity explains planetary motion with no need for meaning. Astronomy and astrology come apart, and astrology loses its place in universities and academies.", where: "Europe" },
      { year: "1930 CE", what: "Clyde Tombaugh discovers Pluto. In the same year a British newspaper runs an astrology column on the birth of Princess Margaret — the seed of the modern sun-sign column.", where: "Flagstaff, USA & London, UK" },
      { year: "1930s–1970s CE", what: "Sun-sign horoscopes spread through newspapers and magazines worldwide. This twelve-boxes-for-everyone format is by far the most recent layer of the tradition.", where: "Worldwide" },
      { year: "2006 CE", what: "The International Astronomical Union defines the term planet and reclassifies Pluto as a dwarf planet. Most astrologers kept using it; the astronomical category had changed, not the object.", where: "Prague" }
    ]
  },

  {
    id: "constellations-vs-signs",
    kind: "chapter",
    title: "A sign is not a constellation (this trips up almost everyone)",
    plain: "Here is the single most useful thing a beginner can learn, and almost nobody is told it plainly: signs and constellations are two different things that happen to share twelve names.\n\nA sign is a measurement. Take the Sun's yearly path around the sky, the ecliptic, and cut it into twelve equal slices of exactly 30° each. Those slices are the signs. They are perfectly regular, they contain no stars by definition, and they are a coordinate system — like lines of longitude, but around the sky.\n\nA constellation is a picture. It is an irregular patch of stars that somebody long ago decided looked like a scorpion or a pair of fish. Constellations are wildly uneven. Along the ecliptic, Virgo sprawls across roughly 44°, while Scorpius occupies only about 7° — six times smaller. The Sun spends about six weeks drifting through the stars of Virgo and barely a week crossing Scorpius.\n\nAnd they no longer line up. When the Greeks fixed the scheme, the sign Aries began roughly where the constellation Aries sat. Earth's slow axial wobble has since slid the two apart by about 24°, close to a whole sign. So in the tropical zodiac used by most Western astrology, being born under the sign Aries usually means the Sun was actually in front of the stars of Pisces. Both facts are true at once, because they are answers to two different questions.",
    deep: "There is a thirteenth constellation on the list too. The Sun's path clips the lower part of Ophiuchus, the Serpent-Bearer, for roughly two and a half weeks each year, between Scorpius and Sagittarius. This is not a discovery and it is not new — the overlap has been known for a very long time, and it was formalised when the International Astronomical Union fixed official constellation boundaries in 1930. Every few years it resurfaces in the press as breaking news that everyone's star sign has changed.\n\nIt has not, and the reason is definitional. Astrology's twelve signs are 30° slices of the ecliptic, not star patterns, so adding a thirteenth star pattern does not add a thirteenth slice. If you want to know which constellation the Sun was genuinely in front of on your birthday, that is a real and answerable astronomical question — and the answer often is Ophiuchus. If you want to know your tropical sun sign, that is a question about seasonal geometry, and Ophiuchus never enters into it.",
    aside: "Same twelve names. Different objects. Different questions."
  },

  {
    id: "precession",
    kind: "fact",
    title: "Why the sky slipped: Earth wobbles",
    plain: "Spin a toy top and watch it slow down. The spin axis starts to lean and swing in a slow cone, tracing a circle in the air while the top keeps spinning underneath. Earth does exactly this. It is tilted about 23.4° from upright, and the Sun and Moon tug on our planet's equatorial bulge, dragging that tilted axis around in a cone.\n\nThe cycle is enormous: about 25,772 years for one full turn. That works out to roughly 1° every 72 years — small enough to miss in a lifetime, obvious across a few centuries, and decisive across a few millennia. This is called the precession of the equinoxes, and the Greek astronomer Hipparchus detected it in the 2nd century BCE by comparing his own star positions with Babylonian records centuries older.\n\nOne consequence you can see: the pole star is temporary. Right now Earth's axis happens to point close to Polaris, which is why it sits almost still while everything else wheels around it. Around 2700 BCE the northern pole star was Thuban in Draco, the star the Egyptian pyramid builders would have used. In roughly 12,000 years the axis will swing near Vega. Eventually it comes back to Polaris, and the whole circuit starts again.\n\nThis is also why the zodiac drifted. The signs are anchored to the equinox, the equinox point creeps backwards along the ecliptic, and the stars stay where they are. Give it two thousand years and the labels and the starfields have parted company.",
    deep: "Precisely, what precesses is the intersection of two planes: Earth's equator and Earth's orbit. Where they cross defines the equinoxes, and that crossing point slides westward along the ecliptic at about 50.3 arcseconds per year. The 25,772-year figure is the time for one complete circuit at the current rate. It is not a perfectly fixed number — the rate varies slightly over long spans, and a separate, much faster wiggle called nutation, driven mainly by the 18.6-year cycle of the Moon's orbital nodes, rides on top of it.\n\nThis is why astronomers always attach an epoch to a star's coordinates, such as J2000.0. Right ascension and declination are measured from the equinox point, and since that point moves, a coordinate without a date is incomplete. Precession is not an obscure correction: it is a routine, continuously applied part of pointing any telescope accurately.",
    aside: "About 1° every 72 years. Slow enough to ignore for a lifetime, fast enough to rearrange the sky over a civilisation.",
    stats: [
      { v: "25,772", u: "years", l: "one full wobble of Earth's axis" },
      { v: "~1°", u: "per 72 years", l: "how far the equinox point slides along the ecliptic" },
      { v: "~50.3", u: "arcseconds per year", l: "the same drift, in the units astronomers actually use" },
      { v: "23.4°", u: "axial tilt", l: "the lean that the wobble carries around in a cone" }
    ]
  },

  {
    id: "tropical-vs-sidereal",
    kind: "compare",
    title: "Two zodiacs, both in use today",
    plain: "Because of precession, anyone building a zodiac has to make a choice: anchor it to the seasons, or anchor it to the stars. You cannot have both, because those two references drift apart. Both choices were made, in different places, and both are still used by millions of people.\n\nThe tropical zodiac pins 0° Aries to the March equinox — the moment the Sun crosses the celestial equator heading north. It is a seasonal framework. Aries always begins when spring begins in the northern hemisphere, permanently, by definition, regardless of what stars are behind the Sun. This is what most Western astrology uses.\n\nThe sidereal zodiac pins the signs to the stars instead, and lets them drift relative to the seasons. Most Indian astrology — Jyotiṣa, often called Vedic astrology — works this way, using a correction factor called the ayanāṃśa to convert between the two frames.\n\nThe gap between them is currently about 24°, a little less than one full sign. So the same birth commonly yields a tropical sun sign one step later than the sidereal one. Neither system is a miscalculation of the other. They are two different conventions, each internally consistent, answering two different questions about where the Sun was.",
    deep: "The offset is not fixed, since it grows by about 1° every 72 years. It also depends on which ayanāṃśa you adopt, because sidereal astrologers do not all agree on exactly where the starry zodiac should start. The Lahiri (Chitrapakṣa) ayanāṃśa, official for Indian calendar purposes, currently sits at roughly 24°, and several other definitions differ from it by up to about a degree.\n\nWorth noting: astronomical coordinates are equinox-based too, which makes the tropical frame closer to standard astronomical practice than people often assume. What astronomers do not do is attach meaning to the resulting positions — the frame is a filing system for where things are, and nothing more.",
    aside: "Two conventions, not a right answer and a wrong answer.",
    aLabel: "Tropical zodiac",
    bLabel: "Sidereal zodiac",
    rows: [
      { label: "What it tracks", a: "The Sun's position relative to the equinoxes — that is, relative to the seasons.", b: "The Sun's position relative to the fixed background stars." },
      { label: "Where 0° Aries sits", a: "At the March equinox point, wherever the stars happen to have drifted to.", b: "At a chosen fixed reference among the stars, near the constellation Aries." },
      { label: "What stays constant", a: "The link to the seasons. Aries always opens northern spring.", b: "The link to the starfields. A sign keeps roughly the same stars behind it." },
      { label: "What drifts", a: "The starfields behind each sign, by about 1° every 72 years.", b: "The seasonal dates of each sign, by about 1° every 72 years." },
      { label: "Current offset", a: "Reference point for the comparison.", b: "About 24° behind the tropical zodiac — nearly one whole sign." },
      { label: "Mainly used by", a: "Most Western astrology, and most sun-sign columns.", b: "Most Indian astrology (Jyotiṣa), and a minority of Western siderealists." },
      { label: "Typical practical effect", a: "A birth in mid-April gives a tropical Sun in Aries.", b: "The same birth usually gives a sidereal Sun in Pisces." }
    ]
  },

  {
    id: "what-astrology-is",
    kind: "note",
    title: "What this site is claiming, and what it isn't",
    plain: "Astrology is a symbolic and cultural tradition roughly three thousand years old. It is one of the great sustained intellectual projects of the ancient world, it drove real advances in mathematics and observation, and it is still meaningful to a very large number of people. It is also, as a system for predicting events or describing personality, something that has been tested many times — with birth data, with control groups, with astrologers matching charts to people they had never met — and it has not shown effects beyond chance. That is the honest state of the evidence, and it has been stable for decades.\n\nAstronomy is what grew out of the same sky-watching. Same observations, same records, same tables — a different set of questions asked of them. The split happened only in the last few centuries, and until then the two were one occupation.\n\nSo, plainly: this site presents astrology as a symbolic language and a piece of cultural history. It does not present it as a predictive or causal one. Everything the site computes about the sky — planetary positions, sign boundaries, aspects, angles, dates — is real astronomy, calculated properly. Where a page describes what a symbol traditionally means, it is reporting what astrologers say, not making a claim about what the planets do. If you enjoy astrology, none of this needs to spoil it. Knowing that a sonnet has fourteen lines because of an Italian convention does not make the sonnet worse.",
    deep: "",
    aside: "Real astronomy underneath. Cultural history on top. Clearly labelled, both ways."
  },

  {
    id: "why-it-persists",
    kind: "chapter",
    title: "Why a three-thousand-year-old system is still around",
    plain: "It is tempting to explain astrology's survival as a failure of education, but that explanation is too cheap and it does not fit the facts. Plenty of people who understand precession perfectly well still read their chart. Something else is going on, and it is genuinely interesting.\n\nPart of it is that astrology is a vocabulary. It gives you about a dozen crisp categories for things that are otherwise hard to name — a restless, initiating quality; a settled, resistant one; a talkative, scattered one. Most people do not have ready-made words for those. Handed a set of images, you start noticing patterns and articulating things you had felt but never phrased. That is a real cognitive service, and it is the same service that Myers-Briggs types, Hogwarts houses and character alignment charts provide. None of them need to be true to be useful as a language.\n\nPart of it is structural. A good symbolic system is generative: twelve signs times twelve houses times ten bodies times a handful of aspects yields effectively unlimited material, all internally consistent, all interpretable. Systems like that are extraordinarily sticky, because they can absorb any new information you bring them without ever breaking. That flexibility is exactly what makes the system unfalsifiable — which is a weakness as science and a strength as a storytelling framework.\n\nAnd part of it is a well-documented quirk of how we read descriptions of ourselves.",
    deep: "The quirk has a name. In 1948 the psychologist Bertram Forer gave his students what he said were individually tailored personality profiles and asked them to rate the accuracy. The average rating was 4.26 out of 5. Every student had received exactly the same text, assembled from a newsstand astrology book — lines like you have a great need for other people to like and admire you, and at times you are extroverted and sociable while at other times you are introverted and wary.\n\nThis is the Barnum or Forer effect, and it is worth stating carefully, because it is often stated badly. It is not a claim that people are gullible, and it does not prove astrology false — a separate body of research does that. What it shows is that statements crafted to be broadly true of most people, while sounding specific, are reliably experienced as personal. The effect strengthens when the reader believes the description was made for them, when it comes from an authority, and when it is mildly flattering.\n\nThe cleanest way to hold all of this: a symbol system says here is a lens for thinking about yourself. A causal claim says Mars at 14° Leo made this happen. The first is a legitimate thing for a tradition to offer. The second is a testable proposition, and it has been tested. Keeping those two apart costs you nothing and keeps you honest.",
    aside: "Forer, 1948: identical profiles handed to every student, rated 4.26 out of 5 for personal accuracy."
  }

];
